ip_address = input("Please enter an IP address: ")
ip_octets = ip_address.split(".")
print(ip_octets)
First = int(ip_octets[0])
Second = int(ip_octets[1])
Third = int(ip_octets[2])
Fourth = int(ip_octets[3])
print("{} : {}".format(First, bin(First) [2:]))
print("{} : {}".format(Second, bin(Second) [2:]))
print("{} : {}".format(Third, bin(Third) [2:]))
print("{} : {}".format(Fourth, bin(Fourth) [2:]))
